### PR TITLE
Try to detect when wrong 'serial' module is installed by mistake

### PR DESCRIPTION
**Pull request by Williangalvani**
Attempt to fix https://github.com/bluerobotics/ping-python/issues/28

### CODE REVIEW

**Comment by Williangalvani** [comment]
> Please
> 
> 1. suggest some commands to fix the serial problem
> 2. take out the future import and put an issue in the future for python2 support if necessary

Done!

**Comment by patrickelectric** [comment]
@jaxxzer

**Comment by jaxxzer** [comment]
And what about every other (many) script we have with this dependency? Should we attempt the same? Should we make some helper lib?

I just want to have some decision on how to apply this precedent going forward.

**Comment by Williangalvani** [comment]
yeah, I don't really like taking 12 lines to import something. But I think we should deal with that somehow

**Comment by jaxxzer** [comment]
I think it's not the program's job to tell the user how to manage dependencies at runtime.

pip will after all install the correct package if the installation is carried out correctly according to the instructions.

I recommend to add this to the relevent readmes (troubleshooting) instead.

**Comment by Williangalvani** [comment]
Sounds good to me!

**Pull request closed without merging**
